[project]
name = "history-trends-unlimited-into-firefox"
version = "1.0.0"
description = "convert browser history from history trends unlimited into firefox"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["pandas>=2.1.4", "tqdm>=4.66.1"]
